### PR TITLE
Rebuild Angular project for publish

### PR DESCRIPTION
**Pull request by rtrick**
ran `ng build --prod` on the results of https://github.com/dreamhaven/frog_ng/pull/2

### CODE REVIEW

**Review by rtgrantm — APPROVED** [review]
I'm not a subject matter expert. These changes seem consistent with what I'd expect from a version update, though.

**Comment by rtjonnyr** [comment]
Are you able to run this locally using `ng serve`?

**Comment by rtjonnyr** [comment]
I'm pulling it down and kicking the tyres on it.

**Review by rtjonnyr — APPROVED** [review]
I was able to serve the frontend locally. Ship it.

**Pull request merged**
